export const browserCoreExamples = [
  "zee browser status",
  "zee browser start",
  "zee browser stop",
  "zee browser tabs",
  "zee browser open https://example.com",
  "zee browser focus abcd1234",
  "zee browser close abcd1234",
  "zee browser screenshot",
  "zee browser screenshot --full-page",
  "zee browser screenshot --ref 12",
  "zee browser snapshot",
  "zee browser snapshot --format aria --limit 200",
];

export const browserActionExamples = [
  "zee browser navigate https://example.com",
  "zee browser resize 1280 720",
  "zee browser click 12 --double",
  'zee browser type 23 "hello" --submit',
  "zee browser press Enter",
  "zee browser hover 44",
  "zee browser drag 10 11",
  "zee browser select 9 OptionA OptionB",
  "zee browser upload /tmp/file.pdf",
  'zee browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "zee browser dialog --accept",
  'zee browser wait --text "Done"',
  "zee browser evaluate --fn '(el) => el.textContent' --ref 7",
  "zee browser console --level error",
  "zee browser pdf",
];
